/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes_pbo;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class GUI extends javax.swing.JFrame {
    String alamatStok;
    String pemesan, hrg, jml, makanan;
    File fileStok;
    BufferedReader baca, bacamnm;
    BufferedWriter tulisStok;
    DefaultTableModel mknTabel;
    DefaultTableModel mnmTabel;
    DefaultTableModel troli;
    String [] data, keranjang;
    public GUI() {
        initComponents();
        mknTabel =(DefaultTableModel)tabelMakanan.getModel();
        mnmTabel =(DefaultTableModel)tabelMinuman.getModel();
//        troli=(DefaultTableModel)tabelPesan.getModel();
        pemesan = pemesanText.getText();
        makanan = makananText.getText();
        jml = jumlahText.getText();
//        jml=jumlah.getText();
        loadData();
    }
    
    public void loadData(){
        mknTabel.getDataVector().removeAllElements();
        String path = "src/data/makanan.txt";
        File file = new  File(path);
        try {
            baca = new BufferedReader(new FileReader(file));
            Object[] dataBaris = baca.lines().toArray();
            for (int i=0; 1<dataBaris.length; i++){
                String baris = dataBaris[i].toString();
                String[] data = baris.split("/");
                mknTabel.addRow(data);
            }
        } catch (Exception e) {
        }
        mnmTabel.getDataVector().removeAllElements();
        String path1 = "src/data/minuman.txt";
        File file1 = new  File(path1);
        try {
            bacamnm = new BufferedReader(new FileReader(file1));
            Object[] dataBarismnm = bacamnm.lines().toArray();
            for (int i=0; 1<dataBarismnm.length; i++){
                String barismnm = dataBarismnm[i].toString();
                String[] datamnm = barismnm.split("/");
                mnmTabel.addRow(datamnm);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jumlahText = new javax.swing.JTextField();
        pemesanText = new javax.swing.JTextField();
        makananText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelMakanan = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelMinuman = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(57, 57, 203));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Makanan", "Harga", "Jumlah", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(430, 370, 452, 210);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jumlah");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 210, 90, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pemesan");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 110, 90, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Makanan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 160, 90, 30);
        jPanel1.add(jumlahText);
        jumlahText.setBounds(150, 220, 210, 30);
        jPanel1.add(pemesanText);
        pemesanText.setBounds(150, 120, 210, 30);
        jPanel1.add(makananText);
        makananText.setBounds(150, 170, 210, 30);

        jButton1.setText("Tambah");
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 280, 90, 30);

        jButton2.setText("Delete");
        jPanel1.add(jButton2);
        jButton2.setBounds(150, 280, 90, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setText("Bayar");
        jPanel1.add(jButton3);
        jButton3.setBounds(40, 490, 110, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total yang harus anda bayarkan");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 390, 230, 30);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(40, 430, 220, 30);

        tabelMakanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Makanan", "Harga", "Ketersediaan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabelMakanan);

        jTabbedPane1.addTab("Makanan", jScrollPane3);

        tabelMinuman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Minuman", "Harga", "Ketersediaan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabelMinuman);

        jTabbedPane1.addTab("Minuman", jScrollPane4);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(430, 120, 450, 230);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jumlahText;
    private javax.swing.JTextField makananText;
    private javax.swing.JTextField pemesanText;
    private javax.swing.JTable tabelMakanan;
    private javax.swing.JTable tabelMinuman;
    // End of variables declaration//GEN-END:variables
}
